<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple control panel">
    <meta name="author" content="BIS-LINUX.COM">
    <link rel="shortcut icon" href="../img/favicon.ico">

    <title>Simple Control Panel</title>

    <!-- Bootstrap core CSS -->
    <link href="../css/bootstrap.min.css" rel="stylesheet">
    <link href="../css/panel.css" rel="stylesheet">
  </head>
  <body>

