   <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Simple Panel</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li@INFO_ACTIVE@><a href="/cgi-bin/info.sh">System info</a></li>
            <li@LED_ACTIVE@><a href="/cgi-bin/leds.sh">LED control</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
